kireidjangoapp/appointments/urls.py
from django.urls import path

from appointments import views

from django.contrib.auth import views as auth_views


app_name = "appointments"

urlpatterns = [
    path("booking/all/", views.all_appointments, name="all_appointments"),
    path("booking/cancel/", views.cancel_appointment, name="cancel_appointment"),
    path("booking/service/", views.choose_service, name="choose_service"),
    path(
        "booking/professional/",
        views.choose_professional,
        name="choose_professional",
    ),
    path("booking/calendar/", views.calendar, name="calendar"),
    path("booking/slot/", views.ChooseSlotView.as_view(), name="choose_slot"),
    path("booking/checkout/", views.checkout, name="checkout"),
    path("booking/detail/", views.appointment_detail, name="appointment_detail"),
    path("booking/success/", views.mercado_pago_success, name="mercado_pago_success"),
    path("booking/failure/", views.mercado_pago_failure, name="mercado_pago_failure"),
]

kireidjangoapp/carts/urls.py
from django.urls import path
from . import views

app_name = "carts"


urlpatterns = [
    path("cart/add/<int:id>/", views.cart_add, name="cart_add"),
    path(
        "cart/item_clear/<int:id>/<str:redirect_url>/",
        views.item_clear,
        name="item_clear",
    ),
    path(
        "cart/item_increment/<int:id>/<str:redirect_url>/",
        views.item_increment,
        name="item_increment",
    ),
    path(
        "cart/item_decrement/<int:id>/<str:redirect_url>/",
        views.item_decrement,
        name="item_decrement",
    ),
    path("cart/cart_clear/", views.cart_clear, name="cart_clear"),
    path("cart/cart_detail/", views.cart_detail, name="cart_detail"),
    path(
        "cart/many_items_add/<int:id>/<int:quantity>/",
        views.many_items_add,
        name="many_items_add",
    ),
    path(
        "cart/catalog_item_increment/<int:id>/",
        views.catalog_item_increment,
        name="catalog_item_increment",
    ),
    path(
        "cart/replace_items_quantity/<int:id>/<int:quantity>/",
        views.replace_items_quantity,
        name="replace_items_quantity",
    ),
    path("cart/checkout/", views.cart_checkout, name="cart_checkout"),
    path("cart/success/", views.mercado_pago_success, name="mercado_pago_success"),
    path("cart/failure/", views.mercado_pago_failure, name="mercado_pago_failure"),
    path("cart/pending/", views.mercado_pago_pending, name="mercado_pago_pending"),
]

kireidjangoapp/home/urls.py
from django.urls import path, include

from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("services/", views.services_index, name="services"),
    path("nosotros/", views.kirei_info, name="kirei_info"),
    path("faq/", views.faq, name="faq"),
]

kireidjangoapp/kireidjangoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("payments/", include("payments.urls")),
    path("", include("home.urls")),
    path("", include(("customers.urls", "customers"), namespace="customers")),
    path("", include(("carts.urls", "carts"), namespace="carts")),
    path("", include(("products.urls", "products"), namespace="products")),
    path("", include(("agendas.urls", "agendas"), namespace="agendas")),
    path("", include(("staff.urls", "staff"), namespace="staff")),
    path("", include(("appointments.urls", "appointments"), namespace="appointments")),
    path("", include(("orders.urls", "orders"), namespace="orders")),
    path("", include(("invoices.urls", "invoices"), namespace="invoices")),
    path("", include(("services.urls", "services"), namespace="services")),
    path(
        "", include(("professionals.urls", "professionals"), namespace="professionals")
    ),
    path("django_plotly_dash/", include("django_plotly_dash.urls")),
]

urlpatterns += staticfiles_urlpatterns()

kireidjangoapp/products/urls.py
from django.urls import path
from . import views
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

app_name = "products"
urlpatterns = [
    path("products/", views.product_catalog, name="product_catalog"),
    path(
        "products/<slug:product_name>-<int:product_id>/",
        views.product_detail,
        name="product_detail",
    ),
    path("staff/product/all", views.all_product, name="all_product"),
    path("staff/product/create", views.create_product, name="create_product"),
    path("staff/product/<int:pk>/edit/", views.edit_product, name="edit_product"),
    path("staff/product/<int:pk>/delete/", views.delete_product, name="delete_product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kireidjangoapp/home/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from django import forms


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50, label="Nombre")
    last_name = forms.CharField(max_length=50, label="Apellido")
    email = forms.EmailField(max_length=150, label="E-mail")
    message = forms.CharField(widget=forms.Textarea, max_length=2000, label="Mensaje")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["first_name"].label = "Nombre"
        self.fields["last_name"].label = "Apellido"
        self.fields["email"].label = "Email"
        self.fields["message"].label = "Mensaje"
        self.helper.layout = Layout(
            "first_name",
            "last_name",
            "email",
            "message",
            Submit("submit", "Enviar", css_class="btn btn-primary mt-3"),
        )

    class Meta:
        template = "crispy_forms/field.html"

kireidjangoapp/home/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, request
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError

from customers.forms import RegisterForm, CustomerLoginForm
from home.forms import ContactForm
from customers.views import signup_view, customer_login
from services.models import Service, CategoryService
from django.core.mail import send_mail
from customers.views import (
    signup_view_from_services,
    customer_login_from_services,
)
from django.contrib import messages


def contact_view(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():

            # Send the email
            subject = 'Solicitud de contacto desde el sitio web de Kirei'
            body = f'''
            Has recibido una solicitud de contacto desde el sitio web de Kirei:

            Nombre: {contact_form.cleaned_data["first_name"]} {contact_form.cleaned_data["last_name"]}
            Email: {contact_form.cleaned_data["email"]}
            Mensaje: 

            {contact_form.cleaned_data["message"]}
            '''

            message = body
            from_email = contact_form.cleaned_data["email"]
            recipient_list = ['iamjunname@gmail.com']

            send_mail(subject, message, from_email, recipient_list, fail_silently=False)
            print("Se envio el email?")
            messages.success(
            request,
            "Mensaje enviado. Te contestaremos a la brevedad."
        )
            return redirect('home:index')
        else:
            print("Form invalido de contacto.")
            messages.error(request, "Error. Mensaje no enviado. Intente más tarde.")
    else:
        contact_form = ContactForm()

    return render(request, "home/index.html", {"contact_form": contact_form})


def index(request):
    
    contact_form = ContactForm()
    register_form = RegisterForm()
    login_form = CustomerLoginForm()
    print("1er Request method:", request.method)

    if request.method == "POST":
        if "contact_form_submit" in request.POST:
            return contact_view(request)
        elif "register_form_submit" in request.POST:
            return signup_view(request)
        elif "login_form_submit" in request.POST:
            return customer_login(request)

    else:
        print("Request method:", request.method)

    context = {
        "contact_form": contact_form,
        "register_form": register_form,
        "login_form": login_form,
        "current_url": request.path,
    }

    return render(request, "home/index.html", context)


def services_index(request):
    services = Service.objects.all()
    categories = CategoryService.objects.all()
    register_form = RegisterForm()
    login_form = CustomerLoginForm()

    if request.method == "POST":
        if "register_form_submit" in request.POST:
            return signup_view_from_services(request)
        elif "login_form_submit" in request.POST:
            return customer_login_from_services(request)
        
    context = {
        "services": services,
        "categories": categories,
        "register_form": register_form,
        "login_form": login_form,
    }

    return render(request, "home/services.html", context)

def kirei_info(request):
    register_form = RegisterForm()
    login_form = CustomerLoginForm()

    if request.method == "POST":
        if "register_form_submit" in request.POST:
            return signup_view(request)
        elif "login_form_submit" in request.POST:
            return customer_login(request)
        
    context = {
        "register_form": register_form,
        "login_form": login_form,
    }
    return render(request, "home/kirei_info.html",context)

def faq(request):
    register_form = RegisterForm()
    login_form = CustomerLoginForm()

    if request.method == "POST":
        if "register_form_submit" in request.POST:
            return signup_view(request)
        elif "login_form_submit" in request.POST:
            return customer_login(request)
        
    context = {
        "register_form": register_form,
        "login_form": login_form,
    }

    return render(request, "home/faq.html",context)

kireidjangoapp/home/templates/home/includes/footer.html
{% load static %}
<footer id="footer" class="footer-1">
    <div class="main-footer widgets-dark typo-light ">
    <div class="container">
    <div class="row">
      
    <div class="col-xs-12 col-sm-6 col-md-4" >
    <div class="widget subscribe no-box mr-auto" >
    <a class="footer-brand"  href="/">
        <img src="{% static 'home/images/logo.png' %}" style="max-width: 55%;
        max-height: 18%;">
    </a>
    </div>
    </div>
    
    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="widget no-box">
            <ul class="thumbnail-widget">
                <li>
                    <div class="thumb-content"><a href="/">Inicio</a></div> 
                </li>
                <li>
                    <div class="thumb-content"><a href="{% url 'home:kirei_info' %}">Nosotros</a></div> 
                </li>
                <li>
                  <div class="thumb-content"><a href="{% url 'home:faq' %}">FAQ</a></div>
                </li>
                <li>
                    <div class="thumb-content"><a href="{% url 'home:services' %}">Servicios</a></div> 
                </li>
            </ul>
        </div>
    </div>
    
    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="widget no-box">
          <h6 class="widget-title widget-title-uppercase">Seguinos en nuestras redes sociales</h6>
          <ul class="social-footer2">
            <li>
              <a title="WhatsApp" target="_blank" href="https://web.whatsapp.com/">
                <i class="fa fa-whatsapp social-icon" aria-hidden="true"></i>
              </a>
            </li>
            <li>
              <a title="Instagram" target="_blank" href="">
                <i class="fa fa-instagram social-icon" aria-hidden="true"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    </div>
    </div>
      
    
</footer>

<div class="footer-copyright">
  <div class="container">
      <div class="row">
          <div class="col-md-12 text-center">
              <p>&copy; Kirei 2023 </p>
          </div>
      </div>
  </div>
</div>

kireidjangoapp/home/templates/home/includes/messages.html
{% if messages %}
  <div class="container-fluid mt-2 pt-2 pb-0 px-0 mb-0 mx-0">
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible mt-5 mb-0 mx-0" role="alert">
        <button type="button" class="close" aria-label="Close" onclick="dismissAlert(this)">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}
  </div>
{% endif %}

<script>
  function dismissAlert(button) {
    const alert = button.closest('.alert');
    alert.remove();
  }
</script>

kireidjangoapp/home/templates/home/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top">
    <a class="navbar-brand" href="/"><img src="{% static 'home/images/logo.png' %}" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      {% if user.is_authenticated %}
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav3">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="btn btn-outline-success btn-booking my-2 my-sm-0" href="/booking/service/">
                Reservar turno
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/products">Comprar productos</a>
            </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Hola, {{user.first_name}}
                </a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="/profile"><i class="fa fa-id-card"></i>  Mi Perfil</a>
                  <a class="dropdown-item" href="/booking/all/"><i class="fa fa-calendar-check-o"></i>  Mis Reservas</a>
                  <a class="dropdown-item" href="/order/all/"><i class="fa fa-shopping-bag "></i>  Mis Compras</a>
                  <a class="dropdown-item" href="/logout"><i class="bi bi-box-arrow-right"></i>  Cerrar Sesión</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'carts:cart_detail' %}">
                  <i class="bi bi-cart-fill"></i>
                  <span class="badge bg-danger">{{ cart_total_quantity }}</span>
                </a>
              </li>
              
          </ul>
        </div>
    {% else%}
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:index'%}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:services' %}">Servicios</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:product_catalog'%}">Productos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'appointments:choose_service'%}">Turnos</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link mr-2" id="modal-open-register-btn" data-toggle="modal" data-target="#registerModal">Registrarme</a>
          </li>
          <li class="nav-item">
            <a class="btn btn-primary" id="modal-open-login-btn" data-toggle="modal" data-target="#loginModal">Ingresar</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">
              <i class="fa fa-shopping-cart"></i>
              <span class="badge badge-pill badge-secondary">{{ cart_total_quantity }}</span>
            </a>
          </li>
        </ul>
      </div>
    {% endif%}
  </nav>

  {% include 'customers/login.html' %} 
  {% include 'customers/register.html' %}
  <script>
    
    {% if value %}
      document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("modal-open-login-btn").click();
      })
    {% endif %}
  
    {% if value_signup %}
      document.addEventListener("DOMContentLoaded", function(){
        document.getElementById("modal-open-register-btn").click();
      })
    {% endif %}
  
  </script>