kireidjangoapp/carts/urls.py
from django.urls import path
from . import views

app_name = "carts"


urlpatterns = [
    path("cart/add/<int:id>/", views.cart_add, name="cart_add"),
    path(
        "cart/item_clear/<int:id>/<str:redirect_url>/",
        views.item_clear,
        name="item_clear",
    ),
    path(
        "cart/item_increment/<int:id>/<str:redirect_url>/",
        views.item_increment,
        name="item_increment",
    ),
    path(
        "cart/item_decrement/<int:id>/<str:redirect_url>/",
        views.item_decrement,
        name="item_decrement",
    ),
    path("cart/cart_clear/", views.cart_clear, name="cart_clear"),
    path("cart/cart_detail/", views.cart_detail, name="cart_detail"),
    path(
        "cart/many_items_add/<int:id>/<int:quantity>/",
        views.many_items_add,
        name="many_items_add",
    ),
    path(
        "cart/catalog_item_increment/<int:id>/",
        views.catalog_item_increment,
        name="catalog_item_increment",
    ),
    path(
        "cart/replace_items_quantity/<int:id>/<int:quantity>/",
        views.replace_items_quantity,
        name="replace_items_quantity",
    ),
    path("cart/checkout/", views.cart_checkout, name="cart_checkout"),
    path("cart/success/", views.mercado_pago_success, name="mercado_pago_success"),
    path("cart/failure/", views.mercado_pago_failure, name="mercado_pago_failure"),
    path("cart/pending/", views.mercado_pago_pending, name="mercado_pago_pending"),
]

kireidjangoapp/home/urls.py
from django.urls import path, include

from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("services/", views.services_index, name="services"),
    path("nosotros/", views.kirei_info, name="kirei_info"),
    path("faq/", views.faq, name="faq"),
]

kireidjangoapp/kireidjangoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("payments/", include("payments.urls")),
    path("", include("home.urls")),
    path("", include(("customers.urls", "customers"), namespace="customers")),
    path("", include(("carts.urls", "carts"), namespace="carts")),
    path("", include(("products.urls", "products"), namespace="products")),
    path("", include(("agendas.urls", "agendas"), namespace="agendas")),
    path("", include(("staff.urls", "staff"), namespace="staff")),
    path("", include(("appointments.urls", "appointments"), namespace="appointments")),
    path("", include(("orders.urls", "orders"), namespace="orders")),
    path("", include(("invoices.urls", "invoices"), namespace="invoices")),
    path("", include(("services.urls", "services"), namespace="services")),
    path(
        "", include(("professionals.urls", "professionals"), namespace="professionals")
    ),
    path("django_plotly_dash/", include("django_plotly_dash.urls")),
]

urlpatterns += staticfiles_urlpatterns()

kireidjangoapp/products/urls.py
from django.urls import path
from . import views
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

app_name = "products"
urlpatterns = [
    path("products/", views.product_catalog, name="product_catalog"),
    path(
        "products/<slug:product_name>-<int:product_id>/",
        views.product_detail,
        name="product_detail",
    ),
    path("staff/product/all", views.all_product, name="all_product"),
    path("staff/product/create", views.create_product, name="create_product"),
    path("staff/product/<int:pk>/edit/", views.edit_product, name="edit_product"),
    path("staff/product/<int:pk>/delete/", views.delete_product, name="delete_product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kireidjangoapp/products/models.py
from django.db import models
from decimal import Decimal


class Product(models.Model):
    CATEGORY_CHOICES = [
        ("cuidado-facial", "Cuidado de la Piel"),
        ("maquillaje", "Maquillaje"),
        ("cuidado-corporal", "Cuidado Corporal"),
        ("perfumes", "Perfumes"),
        ("labios", "Labios"),
        ("cejas", "Cejas"),
        ("ojos", "Ojos"),
        ("nails", "Nails"),
        ("accesorios", "Accesorios"),
        ("baño-y-ducha", "Baño y Ducha"),
        ("exfoliantes", "Exfoliantes"),
        ("hidratantes", "Hidratantes"),
        ("aceites", "Aceites"),
        ("protectores-solares", "Protectores Solares"),
        ("manos", "Manos"),
        ("pies", "Pies"),
    ]
    name = models.CharField(max_length=255)
    description = models.TextField(
        verbose_name="Descripcion del producto",
        default="",
        help_text="Ingrese una breve descripción del producto.",
    )
    price = models.DecimalField(max_digits=15, decimal_places=0, default="")
    stock = models.PositiveIntegerField(default=1)
    image = models.ImageField(upload_to="products/images", null=True, blank=True)
    category = models.CharField(max_length=255, choices=CATEGORY_CHOICES, default="")
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def is_in_stock(self):
        return self.stock > 0

    def get_type(self):
        return "Product"

kireidjangoapp/products/forms.py
from django import forms
from products.models import Product


class ProductForm(forms.ModelForm):
    image = forms.ImageField(label="Imagen")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].label = "Nombre"
        self.fields["description"].label = "Descripción"
        self.fields["price"].label = "Precio"
        self.fields["stock"].label = "Stock"
        self.fields["image"].label = "Imagen"
        self.fields["category"].label = "Categoría"

    class Meta:
        model = Product
        fields = ["name", "description", "price", "stock", "image", "category"]

kireidjangoapp/products/views.py
from django.shortcuts import render
from .models import Product
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Min, Max, Sum
from django.core.paginator import Paginator
from decimal import Decimal, InvalidOperation
from products.forms import ProductForm

from customers.forms import RegisterForm, CustomerLoginForm
from customers.views import signup_view_from_product, customer_login_from_product,customer_login_from_product_detail, signup_view_from_product_detail
from django.contrib import messages


def product_catalog(request):
    all_products = Product.objects.filter(is_available=True)
    products_total = all_products.count()

    categories = Product.objects.values("category").distinct()
    selected_category = request.GET.get("category")

    min_price = Product.objects.aggregate(Min("price"))["price__min"]
    max_price = Product.objects.aggregate(Max("price"))["price__max"]

    # Get the selected price range from the request's GET parameters
    selected_min_price = request.GET.get("min_price")
    selected_max_price = request.GET.get("max_price")

    # Get selected sorting method from request's GET parameters
    selected_sorting = request.GET.get("orderby")

    # Apply selected sorting method to products
    orderby = request.GET.get("orderby")
    if orderby == "price":
        products = all_products.order_by("price")
    elif orderby == "price-desc":
        products = all_products.order_by("-price")
    else:
        products = all_products

    # Get counts of products for each category
    counts = {}
    for category in categories:
        if selected_category:
            count = Product.objects.filter(
                category=category["category"],
                is_available=True,
                category__exact=selected_category,
            ).count()
        else:
            count = Product.objects.filter(
                category=category["category"], is_available=True
            ).count()
        counts[category["category"]] = count

    # Get counts of products for each category
    category_counts = {}
    for category in categories:
        count = Product.objects.filter(
            category=category["category"], is_available=True
        ).count()
        category_counts[category["category"]] = count

    # Filter products by selected category
    if selected_category:
        products = products.filter(category=selected_category, is_available=True)
    else:
        products = products.filter(is_available=True)

    # Apply selected price range filter
    if selected_min_price and selected_max_price:
        products = products.filter(
            price__gte=selected_min_price, price__lte=selected_max_price
        )

    paginator = Paginator(products, 15)
    page_number = request.GET.get("page")

    page_obj = paginator.get_page(page_number)

    # Login & register when not authenticated
    register_form = RegisterForm()
    login_form = CustomerLoginForm()

    context = {
        "products": products,
        "products_total": products_total,
        "categories": categories,
        "selected_category": selected_category,
        "min_price": min_price,
        "max_price": max_price,
        "page_obj": page_obj,
        "is_paginated": paginator.num_pages > 1,
        "counts": counts,
        "category_counts": category_counts,
        "selected_min_price": selected_min_price,
        "selected_max_price": selected_max_price,
        "selected_sorting": selected_sorting,
        "register_form": register_form,
        "login_form": login_form,
    }

    if request.method == "POST":
        if "register_form_submit" in request.POST:
            return signup_view_from_product(request, context)
        elif "login_form_submit" in request.POST:
            return customer_login_from_product(request, context)

    return render(request, "products/products_catalog.html", context)


def product_detail(request, product_name, product_id):
    product = get_object_or_404(Product, pk=product_id)
    # Login & register when not authenticated
    register_form = RegisterForm()
    login_form = CustomerLoginForm()

    context={
        "product": product, 
         "id": product_id,
         "register_form": register_form,
         "login_form": login_form
    }

    if request.method == "POST":
        if "register_form_submit" in request.POST:
            return signup_view_from_product_detail(request, context)
        elif "login_form_submit" in request.POST:
            return customer_login_from_product_detail(request, context)

    return render(
        request, "products/product_detail.html", context
        
    )


# Staff panel product
def all_product(request):
    products = Product.objects.all()
    return render(request, "products/product_list.html", {"products": products})


def create_product(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("products:all_product")
    else:
        form = ProductForm()
    return render(request, "products/product_form.html", {"form": form})


def edit_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect("products:all_product")
    else:
        form = ProductForm(instance=product)
    return render(
        request, "products/edit_product.html", {"form": form, "product": product}
    )


def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        product.delete()
        return redirect("products:all_product")
    return render(request, "products/product_list.html", {"product": product})

kireidjangoapp/products/templates/products/edit_product.html
{% extends 'staff/base.html'%}
{% block breadcrumb-item %}<a class="breadcrumb-item" href="{% url 'products:all_product'%}">Productos</a>{% endblock %}
{% block breadcrumb-item-active %}Editar producto{% endblock %}
{% block title %}Editar producto{% endblock %}
{% block content %}
{% load crispy_forms_tags %}

<div class="card shadow mb-4">
  
  <div class="card-body">
    <div class="row justify-content-sm-center h-100">
      <div class="col-xxl-4 col-xl-5 col-lg-5 col-md-7 col-sm-9">
        <form method="POST" class="needs-validation" novalidate="" autocomplete="off" id="edit-product-form">
          <div class="mb-3">
                {% csrf_token %}
                {{ form|crispy }}
          </div>
          <div class="mb-3">
            <div class="d-flex align-items-center">
                <button id="submit_edit" type="submit" class="btn btn-primary m-1">
                    Guardar
                </button>
                <a href="{% url 'products:all_product' %}" class="btn btn-secondary m-1">
                  Cancelar
                </a>
                
            </div>
          </div>    
      </form>
      </div>
  </div>
  </div>
</div>


<script>
  document.addEventListener("DOMContentLoaded", () => {
    const submitBtn = document.querySelector("#submit_edit");
    const form = document.querySelector("#edit-product-form");

    submitBtn.addEventListener("click", async (event) => {
      event.preventDefault();

      // Check if any input (excluding file input) is empty
      const inputs = form.querySelectorAll("input:not([type='file']), textarea");
      let isEmpty = false;
      inputs.forEach((input) => {
        if (input.value.trim() === "") {
          isEmpty = true;
        }
      });

      if (isEmpty) {
        Swal.fire({
          title: "Error",
          text: "Por favor, complete todos los campos.",
          icon: "error",
          showCloseButton: true,
          showConfirmButton: false,
        });
        return;
      }

      try {
        const productId = {{ product.id }};
        const response = await fetch("/staff/product/" + productId + "/edit/", {
          method: "POST",
          body: new FormData(form),
        });

        if (response.ok) {
          await Swal.fire({
            title: "Se editó el producto exitosamente.",
            icon: "success",
            confirmButtonText: "OK",
          });
          window.location.href = "/staff/product/all";
        } else {
          const modalContent = await response.json();

          Swal.fire({
            title: modalContent.title,
            text: modalContent.text,
            icon: "error",
            showCloseButton: true,
            showConfirmButton: false,
          });
          window.location.href = "/staff/product/all";
        }
      } catch (error) {
        Swal.fire({
          title: "Error",
          text: "Intente más tarde o comuníquese con el Administrador.",
          icon: "error",
          showCloseButton: true,
          showConfirmButton: false,
        });
      }
    });
  });
</script>


{% endblock %}

kireidjangoapp/products/templates/products/product_list.html
{% extends 'staff/base.html'%}
{% block breadcrumb-item %}<a class="breadcrumb-item" href="{% url 'products:all_product'%}">Productos</a>{% endblock %}
{% block breadcrumb-item-active %}Todos los productos{% endblock %}
{% block content %}
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="h3 mb-0 text-gray-800 d-inline-block align-middle">Todos los productos</h1>
    </div>
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
                    
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Categoría</th>
                            <th>Precio</th>
                            <th>Stock</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Nombre</th>
                            <th>Categoría</th>
                            <th>Precio</th>
                            <th>Stock</th>
                        </tr>
                    </tfoot>
                    
                    <tbody>
                        {% for c in products %}
                                <tr>
                                    <td class="d-flex flex-direction-row align-items-center">
                                        <div class="mr-auto">
                                            <img class="card-img" style="max-width: 100px; max-height: 100px;" src="{{ c.image.url }}" alt="{{ c.name }}">
                                        </div>
                                        <div class="me-auto">{{ c.name }}</div>
                                        <div class="ml-auto">
                                            <a class="px-2 py-1 mr-1 btn btn-secondary" href="{% url 'products:edit_product' c.pk %}">
                                                <i class="bi bi-pencil-square"></i>
                                            </a>
                                            <a class="px-2 py-1 btn btn-danger delete-product" data-id="{{ c.pk }}">
                                                <i class="bi bi-trash"></i>
                                            </a>
                                        </div>
                                    </td>
                                    <td class="align-middle">{{ c.get_category_display }}</td>
                                    <td class="align-middle">$ {{ c.price }}</td>
                                    <td class="align-middle">{{ c.stock }}</td>    
                                </tr>
                        {% endfor %}
                    </tbody>  
                </table>
            </div>
        </div>
    </div>

    <script>
        $(function() {
      
      // Handle the delete of an agenda
      $('.delete-product').on('click', function() {
          var agendaId = $(this).data('id');
          var csrftoken = getCookie('csrftoken'); // get the CSRF token value from the cookie
        
          Swal.fire({
            title: '¿Estás seguro que desea eliminar este producto?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Sí, eliminar',
            cancelButtonText: 'Cancelar',
          }).then((result) => {
            if (result.isConfirmed) {
              $.ajax({
                url: '/staff/product/' + agendaId + '/delete/',
                type: 'post',
                headers: {'X-CSRFToken': csrftoken}, // include the CSRF token in the header
                success: function(data) {
                  location.href = location.href;
                  window.location.href = '/staff/product/all';
                },
                error: function(xhr, textStatus, errorThrown) {
                  console.log(xhr.responseText);
                }
              });
            }
          });
        });
        
        // Function to get the value of the CSRF token from the cookie
        function getCookie(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                  var cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
        }
        
          
      });
         
    </script>
{% endblock %}

kireidjangoapp/products/templates/products/products_catalog.html
{% extends 'home/base.html' %}

{% load static %}
{% load my_filters %}


{% block content %}


<div class="container mt-5 pt-5">
  <div class="row">
    <div class="col-md-3 py-5">
      <div class="container-breadcrumb">
        <nav class="breadcrumb">
          <a class="breadcrumb-item text-secondary" href="/">Inicio</a>
          <span class="breadcrumb-item active">Tienda</span>
        </nav>
      </div>
      <div class="card mt-5">
        <div class="card-body">
          <h5 class="card-title">Filtrar por precio</h5>

          <form method="GET" action="{% url 'products:product_catalog'%}">
            <div class="price_slider_wrapper position-relative my-4">
              <div class="d-flex justify-content-center">
                <input id="price_slider" 
                       type="range"
                       class="position-absolute top-0 start-50 translate-middle-x w-100 bg-transparent slider-primary" 
                       value="{{ selected_min_price|default:min_price }},{{ selected_max_price|default:max_price }}"
                       min="{{ min_price }}"
                       max="{{ max_price }}"
                       step="10"
                       oninput="updatePriceLabels()"/>                       
              </div>
          
              <div class="row g-0 align-items-center price_slider_amount my-4">
                <div class="col-8 text-center">
                  <div class="price_label">
                    <label class="visually-hidden" for="min_price">Precio mínimo</label>
                    <input type="text" id="min_price" name="min_price" value="{{ selected_min_price|default:min_price }}" data-min="{{ min_price }}" placeholder="Precio mínimo" class="form-control" style="display: none;">
                    <label class="visually-hidden" for="max_price">Precio máximo</label>
                    <input type="text" id="max_price" name="max_price" value="{{ selected_max_price|default:max_price }}" data-max="{{ max_price }}" placeholder="Precio máximo" class="form-control" style="display: none;">
                    Desde: <span class="from">${{ selected_min_price|default:min_price }}</span>  <span class="to visually-hidden">—${{ selected_max_price|default:max_price }}</span>
                  </div>
                </div>
                <div class="col-4 text-end">
                  <button type="submit" class="btn btn-primary">Filtrar</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
            <div class="form-group">
                <h5 for="category">Categorías</h5>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="?category=" class="text-muted{% if not selected_category %}active{% endif %}" style="text-decoration: none;">Todos</a>
                        <span class="badge badge-secondary badge-pill">{{ products_total }}</span>
                    </li>
                    {% for category in categories %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                      <a href="?category={{ category.category }}" class="text-muted{% if category.category == selected_category %}active{% endif %}" style="text-decoration: none;">
                        {{ category.category|convert_category_key }}
                      </a>
                        {% for name, cont in category_counts.items %}
                          {% if name == category.category %}
                            <span class="badge badge-secondary badge-pill">{{ cont }}</span>
                          {% endif %}
                          
                        {% endfor %}
                    </li>
                  {% endfor %}
                </ul>            
            </div>
        </div>
    </div>
    </div>
    <div class="col-md-9">
      <div class="container">
        <div class="row align-items-center mt-0">
          <div class="col-12 my-2">
            <h1 class="">Tienda</h1>
          </div>
        </div>
        <div class="row align-items-center mb-2">
          <div class="col-12 col-md-6">
            <p class="mb-0">Mostrando los {{ products.count }} resultados</p>
          </div>
          <div class="col-12 col-md-6 ">
            <form method="GET" action="{% url 'products:product_catalog'%}" class="form-inline d-flex justify-content-end" id="product-search-form">
              <label class="visually-hidden mr-2" for="orderby">Filtros</label>
              <select class="form-control" id="orderby" name="orderby" onchange="this.form.submit()">
                  <option>Ordene por ...</option>
                  <option value="price" {% if selected_orderby == 'price' %}selected{% endif %}>Ordenar por menor precio</option>
                  <option value="price-desc" {% if selected_orderby == 'price-desc' %}selected{% endif %}>Ordenar por mayor precio</option>
              </select>
              <input type="hidden" name="min_price" value="{{ selected_min_price|default:min_price }}">
              <input type="hidden" name="max_price" value="{{ selected_max_price|default:max_price }}">
            </form>
            
          
          </div>
        </div>

        {% if products %}
        
  <div class="row">
    {% for product in products %}
      <div class="col-12 col-md-4 mb-4">
        <div class="card"> 
          <a href="{% url 'products:product_detail' product_name=product.name|slugify product_id=product.id %}">
            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}" style="height: 400px;">
          </a>
          <div class="card-body">
            <h7 class="card-category text-muted">{{ product.get_category_display }}</h7>
            <h4 class="card-title mb-5" style="height: 70px;">
              <a href="{% url 'products:product_detail' product_name=product.name|slugify product_id=product.id %}" style="text-decoration: none;color:black;">
                <strong>{{ product.name }}</strong>
              </a>
            </h4>
            <span class="price-amount">
              <bdi>
                <span class="price-currency-symbol">$</span>{{ product.price }}
              </bdi>
            </span>
            <br>
            {% if product.stock == 0  %}
            <a href=""  class="btn btn-secondary mt-3 disabled">SIN STOCK</a>
            {% elif product.stock >= 1 %}
            <a data-authenticated="{{ request.user.is_authenticated|lower }}" id="add-to-cart-btn-{{ product.id }}" href="{% url 'carts:catalog_item_increment' product.id %}" data-quantity="1" class="btn btn-primary mt-3" data-product_id="{{ product.id }}" aria-label="Añade {{ product.name }} a tu carrito" rel="nofollow">Añadir al carrito</a>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% if is_paginated %}
  <nav aria-label="Product pages">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if selected_category %}&category={{ selected_category }}{% endif %}{% if min_price %}&min_price={{ min_price }}{% endif %}{% if max_price %}&max_price={{ max_price }}{% endif %}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Anterior</span>
          </a>
        </li>
      {% endif %}
      {% for page in page_obj.paginator.page_range %}
        {% if page_obj.number == page %}
          <li class="page-item active"><a class="page-link" href="#">{{ page }}</a></li>
        {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
          <li class="page-item"><a class="page-link" href="?page={{ page }}{% if selected_category %}&category={{ selected_category }}{% endif %}{% if min_price %}&min_price={{ min_price }}{% endif %}{% if max_price %}&max_price={{ max_price }}{% endif %}">{{ page }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if selected_category %}&category={{ selected_category }}{% endif %}{% if min_price %}&min_price={{ min_price }}{% endif %}{% if max_price %}&max_price={{ max_price }}{% endif %}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Siguiente</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

{% else %}
  <p>No se encontraron productos.</p>
{% endif %}

  </div>
</div>

<script>

  function updatePriceLabels() {
    var priceSlider = document.getElementById("price_slider");
  var minPrice = priceSlider.value.split(",")[0];
  var maxPrice = priceSlider.value.split(",")[1];
  if (maxPrice) {
    document.getElementById("max_price").value = maxPrice;
    document.querySelector(".to").innerHTML = "$" + maxPrice;
  }
  document.getElementById("min_price").value = minPrice;
  document.querySelector(".from").innerHTML = "$" + minPrice;
  }

  const orderbySelect = document.getElementById("orderby");
orderbySelect.addEventListener("change", function() {
  document.getElementById("product-search-form").submit();
});





// Show login modal
function showLoginModal() {
  $('#loginModal').modal('show');
  console.log("showing login modal");
}
// Close login modal
function closeLoginModal() {
  $('#loginModal').modal('hide');
}

window.addEventListener('DOMContentLoaded', function() {
// for
  {% for product in products %}
  var addToCartBtn = document.getElementById('add-to-cart-btn-'+{{ product.id }});
      addToCartBtn.addEventListener('click', function(event) {
      // Check if the user is not authenticated
      var isAuthenticated = addToCartBtn.getAttribute('data-authenticated');
      if (isAuthenticated === 'false') {
        event.preventDefault(); // Prevent the default link behavior
        showLoginModal();
      }
  });
  {% endfor %}
  // end for
})

// Add event listener to the close button
const closeBtn = document.querySelector('#close-login-modal-btn');
closeBtn.addEventListener('click', closeLoginModal);

function showLoginModalFromRegister() {
  var registerModalButton = document.getElementById("register-modal-btn");

  // Close registerModal manually
  registerModalButton.click();

  
}

// Attach the event listener for the "Ingresá" link
document.getElementById("login-link").addEventListener("click", function (event) {
  event.preventDefault(); // Prevent the default link behavior
  showLoginModalFromRegister();
  console.log("show login modal from register")
});

{% if value %}
    document.addEventListener("DOMContentLoaded", function() {
      document.getElementById("modal-open-login-btn").click();
    })
{% endif %}
{% if value_signup %}
  document.addEventListener("DOMContentLoaded", function(){
    document.getElementById("modal-open-register-btn").click();
  })
{% endif %}





</script>


<style>
  select {
    -webkit-appearance: menulist !important;
    -moz-appearance: menulist !important;
    appearance: menulist !important;
  }
</style>


{% endblock %}