kireidjangoapp/agendas/urls.py
from django.urls import path

from agendas import views

from django.contrib.auth import views as auth_views


app_name = "agendas"

urlpatterns = [
    path("agenda/all", views.all_agenda, name="all_agenda"),
    path("agenda/create", views.create_agenda, name="create_agenda"),
    path("agenda/<int:pk>/edit", views.edit_agenda, name="edit_agenda"),
    path(
        "agenda/<int:pk>/day_modification",
        views.day_modification,
        name="day_modification",
    ),
    path("agenda/<int:pk>/delete/", views.delete_agenda, name="delete_agenda"),
    path(
        "agenda/modifications/all",
        views.agenda_modifications_list,
        name="all_modifications_agenda",
    ),
    path(
        "agenda/modification/<int:pk>/delete/",
        views.agenda_modification_delete,
        name="agenda_modification_delete",
    ),
]

kireidjangoapp/home/urls.py
from django.urls import path, include

from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("services/", views.services_index, name="services"),
    path("nosotros/", views.kirei_info, name="kirei_info"),
    path("faq/", views.faq, name="faq"),
]

kireidjangoapp/invoices/urls.py
from django.urls import path
from . import views

app_name = "invoices"

urlpatterns = [
    path(
        "factura/<int:order_id>-<int:product_id>/",
        views.generate_invoice,
        name="generate_invoice",
    ),
]

kireidjangoapp/kireidjangoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("payments/", include("payments.urls")),
    path("", include("home.urls")),
    path("", include(("customers.urls", "customers"), namespace="customers")),
    path("", include(("carts.urls", "carts"), namespace="carts")),
    path("", include(("products.urls", "products"), namespace="products")),
    path("", include(("agendas.urls", "agendas"), namespace="agendas")),
    path("", include(("staff.urls", "staff"), namespace="staff")),
    path("", include(("appointments.urls", "appointments"), namespace="appointments")),
    path("", include(("orders.urls", "orders"), namespace="orders")),
    path("", include(("invoices.urls", "invoices"), namespace="invoices")),
    path("", include(("services.urls", "services"), namespace="services")),
    path(
        "", include(("professionals.urls", "professionals"), namespace="professionals")
    ),
    path("django_plotly_dash/", include("django_plotly_dash.urls")),
]

urlpatterns += staticfiles_urlpatterns()

kireidjangoapp/products/urls.py
from django.urls import path
from . import views
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

app_name = "products"
urlpatterns = [
    path("products/", views.product_catalog, name="product_catalog"),
    path(
        "products/<slug:product_name>-<int:product_id>/",
        views.product_detail,
        name="product_detail",
    ),
    path("staff/product/all", views.all_product, name="all_product"),
    path("staff/product/create", views.create_product, name="create_product"),
    path("staff/product/<int:pk>/edit/", views.edit_product, name="edit_product"),
    path("staff/product/<int:pk>/delete/", views.delete_product, name="delete_product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kireidjangoapp/staff/urls.py
from django.urls import path
from . import views
from agendas.views import create_agenda, edit_agenda
from django.contrib.auth import views as auth_views


app_name = "staff"

urlpatterns = [
    path(
        "staff/orders_dashboard",
        views.staff_orders_dashboard,
        name="staff_orders_dashboard",
    ),
    path(
        "staff/orders-details/<int:order_id>-<int:product_id>/",
        views.orders_details,
        name="orders_details",
    ),
    path(
        "staff/statistic_dashboard",
        views.staff_statistic_dashboard,
        name="staff_statistic_dashboard",
    ),
    path(
        "staff/appointments_dashboard",
        views.staff_appointments_dashboard,
        name="staff_appointments_dashboard",
    ),
    path(
        "staff/create_appointment",
        views.staff_create_appointment,
        name="staff_create_appointment",
    ),
    path(
        "staff/customers_dashboard",
        views.staff_customers_dashboard,
        name="staff_customers_dashboard",
    ),
    path(
        "staff/main_dashboard", views.staff_main_dashboard, name="staff_main_dashboard"
    ),
    path("staff/login/", views.staff_login, name="staff_login"),
    path("staff/logout/", views.staff_logout, name="staff_logout"),
    path(
        "staff/appointments_dashboard/cancel/",
        views.staff_cancel_appointment,
        name="staff_cancel_appointment",
    ),
    path("staff/not-available/", views.not_available, name="not_available"),
    path(
        "staff/password_reset/", views.staff_password_reset, name="staff_password_reset"
    ),
    path(
        "staff/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="staff/password/password_reset_done.html"
        ),
        name="staff_password_reset_done",
    ),
    path(
        "staff/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="staff/password/password_reset_confirm.html"
        ),
        name="staff_password_reset_confirm",
    ),
    path(
        "staff/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="staff/password/password_reset_complete.html"
        ),
        name="staff_password_reset_complete",
    ),
]

kireidjangoapp/staff/models.py
from django.db import models

# Create your models here.

kireidjangoapp/staff/forms.py
from allauth.account.forms import LoginForm
from crispy_forms.helper import FormHelper


class StaffLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields["login"].label = "Email"
        self.fields["password"].label = "Contraseña"
        self.helper.form_method = "post"
        self.fields["password"].widget.attrs["placeholder"] = ""
        self.fields["login"].widget.attrs["placeholder"] = ""
        self.fields["login"].widget.attrs.update({"class": "form-control my-2"})
        self.fields["password"].widget.attrs.update({"class": "form-control my-2"})

kireidjangoapp/staff/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from staff.forms import StaffLoginForm
from django.contrib.auth import authenticate
from agendas.models import Agenda
from orders.models import ProductOrder
from products.models import Product
from professionals.models import Professional
from customers.models import Customer
from appointments.models import Appointment
from my_payments.models import ProductPayment, AppointmentPayment, CartPayment
from django_plotly_dash import DjangoDash
from dash import dcc, html
from dash.dependencies import Input, Output
import dash_bootstrap_components as dbc
import dash
import pandas as pd
import plotly.graph_objs as go
from services.models import Service, CategoryService
import plotly.express as px
from django.db.models import Count
from django.db.models.functions import Trunc
from orders.models import AppointmentOrder, ProductOrder
import datetime
import numpy as np
from django.views.decorators.http import require_GET
from django.urls import reverse
from itertools import groupby
from django.db.models import Sum
from datetime import date
from django.db.models import Q
from django.contrib.auth.forms import PasswordResetForm
from django.core.mail import send_mail, BadHeaderError
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import login, logout
from django.contrib import messages


# STATISTICS
# Create a new Dash app
app = DjangoDash(
    "staff_statistic_dashboard", external_stylesheets=[dbc.themes.BOOTSTRAP]
)

app.layout = dbc.Container(
    [
        dbc.Row(
            [
                dbc.Col(dcc.Graph(id="products-category-chart"), width=6),
                dbc.Col(dcc.Graph(id="agenda-graph"), width=6),
            ]
        ),
        dbc.Row(
            [
                dbc.Col(dcc.Graph(id="category-service-chart"), width=6),
                dbc.Col(dcc.Graph(id="professional-graph"), width=6),
            ]
        ),
        dbc.Row(
            [
                dbc.Col(dcc.Graph(id="payment-chart"), width=8),
                dbc.Col(dcc.Graph(id="customer-graph"), width=4),
            ]
        ),
        dbc.Row(
            [
                dbc.Col(dcc.Graph(id="most-reserved-service-graph"), width=12),
            ]
        ),
        dbc.Row(
            [
                dbc.Col(dcc.Graph(id="appointment-day-count"), width=12),
            ]
        ),
        dbc.Row(
            [
                dbc.Col(html.H3("Cantidad de reservas")),
                dcc.Dropdown(
                    id="time-period",
                    options=[
                        {"label": "Por mes", "value": "month"},
                        {"label": "Por año", "value": "year"},
                    ],
                    value="month",
                ),
                dcc.Graph(id="appointment-count"),
            ]
        ),
        dbc.Row([dbc.Col(dcc.Graph(id="most-ordered-product"), width=12)]),
    ],
    fluid=True,
)


@app.callback(
    dash.dependencies.Output("category-service-chart", "figure"),
    [dash.dependencies.Input("category-service-chart", "hoverData")],
)
def category_service_chart(hoverData):
    categories = dict(CategoryService.objects.values_list("id", "category"))

    services = Service.objects.all().select_related("category")
    df_services = pd.DataFrame.from_records(
        services.values("id", "service", "category__id")
    )

    # Replace the category IDs with their human-readable names
    df_services["category"] = df_services["category__id"].apply(
        lambda x: categories.get(x)
    )

    # Count the number of services in each category
    service_counts = df_services["category"].value_counts()

    colors = ["#CC89CB", "#D36378", "#7F3C56", "#D98B9D", "#472333", "#C92E4F"]

    # Create a bar chart to display the results
    fig = go.Figure(
        data=[
            go.Bar(
                x=service_counts.index,
                y=service_counts.values,
                text=service_counts.values,
                textposition="auto",
                marker=dict(color=colors),
            )
        ],
        layout={
            "title": "Cantidad de servicios x Categoría",
            "xaxis_title": "Categoría",
            "yaxis_title": "Cantidad de Servicios",
            "yaxis": dict(tickmode="linear", tick0=1, dtick=1),
        },
    )

    return fig


# Productos x categoria
@app.callback(
    dash.dependencies.Output("products-category-chart", "figure"),
    [dash.dependencies.Input("products-category-chart", "hoverData")],
)
def products_category_chart(hoverData):
    products = Product.objects.all()
    category_counts = Product.objects.values("category").annotate(count=Count("id"))

    # create a list of the category labels and counts
    labels = [item["category"] for item in category_counts]
    counts = [item["count"] for item in category_counts]

    # create a pie chart trace
    trace = go.Pie(labels=labels, values=counts)

    # create the figure layout
    layout = go.Layout(title="Productos x Categorías")

    # create the figure object
    fig = go.Figure(data=[trace], layout=layout)

    # return the figure object
    return fig


# Cantidad de Agendas según horario de inicio
@app.callback(
    dash.dependencies.Output("agenda-graph", "figure"),
    [dash.dependencies.Input("agenda-graph", "hoverData")],
)
def update_agenda_graph(hoverData):
    # Query the database to get the counts per start_time
    agenda_counts = (
        Agenda.objects.values("start_time")
        .annotate(count=Count("id"))
        .order_by("start_time")
    )

    # Create the Plotly figure
    fig = {
        "data": [
            {
                "labels": [agenda["start_time"] for agenda in agenda_counts],
                "values": [agenda["count"] for agenda in agenda_counts],
                "type": "pie",
            }
        ],
        "layout": {"title": "Cantidad de Agendas según horario de inicio"},
    }
    return fig


# Cantidad de profesionales por día
@app.callback(
    dash.dependencies.Output("professional-graph", "figure"),
    [dash.dependencies.Input("professional-graph", "hoverData")],
)
def update_professional_graph(hoverData):
    # Query the database to get the counts per start_date
    professional_counts = (
        Professional.objects.annotate(start_day=Trunc("start_date", "day"))
        .values("start_day")
        .annotate(count=Count("id"))
        .order_by("start_day")
    )

    # Create a DataFrame from the queryset
    df = pd.DataFrame(professional_counts)

    df["start_day"] = pd.to_datetime(df["start_day"])

    fig = go.Figure()

    bar_trace = go.Bar(
        x=df["start_day"],
        y=df["count"],
        name="Cantidad de profesionales",
    )

    fig.add_trace(bar_trace)

    fig.update_layout(
        title="Cantidad de profesionales nuevos por día",
        xaxis=dict(
            title="Fecha de inicio",
            tickformat="%Y-%m-%d",
            tickmode="array",
            tickvals=df["start_day"],
            ticktext=df["start_day"].dt.strftime("%Y-%m-%d"),
            dtick="M1",  # Display ticks every 1 month
        ),
        yaxis=dict(title="Cantidad de profesionales"),
    )

    fig.update_yaxes(tickmode="linear", dtick=1)

    # Display the chart
    return fig


# Ganancias Totales por día
@app.callback(
    dash.dependencies.Output("payment-chart", "figure"),
    [dash.dependencies.Input("payment-chart", "hoverData")],
)
def update_payment_chart(hoverData):
    appointment_orders = AppointmentOrder.objects.all()
    cart_orders = ProductOrder.objects.all()

    # Create a list of dates and corresponding total payments for appointment orders
    appointment_dates = []
    appointment_totals = []
    for order in appointment_orders:
        date = order.created_at.date()
        if date in appointment_dates:
            appointment_totals[-1] += order.payment.total
        else:
            appointment_dates.append(date)
            appointment_totals.append(order.payment.total)

    # Create a list of dates and corresponding total payments for cart orders
    cart_dates = []
    cart_totals = []
    for order in cart_orders:
        date = order.created_at.date()
        if date in cart_dates:
            cart_totals[-1] += order.payment.cart_total
        else:
            cart_dates.append(date)
            cart_totals.append(order.payment.cart_total)

    # Create the plotly figure
    fig = go.Figure()

    # Add a trace for appointment payments
    fig.add_trace(
        go.Scatter(
            x=appointment_dates,
            y=appointment_totals,
            mode="lines",
            name="Ganancias x Turnos",
        )
    )

    # Add a trace for cart payments
    fig.add_trace(
        go.Scatter(x=cart_dates, y=cart_totals, mode="lines", name="Ganancias x Venta de productos")
    )

    # Set the x-axis label
    fig.update_xaxes(title_text="Fecha")

    # Set the y-axis label
    fig.update_yaxes(title_text="Ganancia Total")

    # Set the title of the figure
    fig.update_layout(title_text="Ganancias Totales por día")

    # Return the updated figure

    return fig


# Cantidad Total de Clientes
@app.callback(
    Output("customer-graph", "figure"), [Input("customer-graph", "hoverData")]
)
def update_customer_graph(n_clicks):
    total_customers = Customer.objects.filter(
        ~Q(is_admin=True) & ~Q(is_staff=True)
    ).count()
    
    
    fig = {
        "data": [
            {
                "x": ["Clientes totales"],
                "y": [total_customers],
                "type": "bar",
                "text": total_customers,
                "textposition": "auto",
            }
        ],

kireidjangoapp/staff/templates/staff/appointments_dashboard.html
{% extends 'staff/base.html'%}

{% block breadcrumb-item %}<a class="breadcrumb-item" href="{% url 'staff:staff_appointments_dashboard'%}">Turnos</a>{% endblock %}
{% block breadcrumb-item-active %}Todos los turnos{% endblock %}
{% block content %}

{% include 'home/includes/messages.html' %}
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="h3 mb-0 text-gray-800 d-inline-block align-middle">Todos los turnos</h1>
    </div>
    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
                    
                    <thead>
                        <tr>
                            <th>Fecha</th>
                            <th>Profesional</th>
                            <th>Servicio</th>
                            <th>Horario</th>
                            <th>Cliente</th>
                            <th>Cancelar reserva</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Fecha</th>
                            <th>Profesional</th>
                            <th>Servicio</th>
                            <th>Horario</th>
                            <th>Cliente</th>
                            <th>Cancelar reserva</th>
                        </tr>
                    </tfoot>
                    
                    <tbody>
                        {% for group in grouped_appointments %}
                            {% with appointment=group.appointments.0 %}
                                <tr style="text-align: center;">
                                    <td>{{ group.date }}</td>
                                    <td>{{ group.professional }}</td>
                                    <td>{{ group.service }}</td>
                                    <td>{{ appointment.start_time }}</td>
                                    <td>{{ group.customer.first_name }} {{ group.customer.last_name}}</td>
                                    <td>
                                        <span class="btn btn-danger">
                                            <a style="color:white; font-style: normal !important;" href="{% url 'staff:staff_cancel_appointment' %}?ids={% for appointment in group.appointments %}{{ appointment.id }}{% if not forloop.last %},{% endif %}{% endfor %}">
                                                <i class="bi bi-trash"></i>
                                            </a>
                                        </span>
                                    </td>
                                </tr>
                            {% endwith %}
                        {% endfor %}
                
                    </tbody>  
                    
                </table>
            </div>
        </div>
    </div>

   
{% endblock %}

kireidjangoapp/staff/templates/staff/create_appointment.html
{% extends 'staff/base.html' %}

{% block breadcrumb-item %}
  <a class="breadcrumb-item" href="{% url 'staff:staff_appointments_dashboard' %}">Turnos</a>
{% endblock %}

{% block breadcrumb-item-active %}Nuevo turno{% endblock %}

{% block content %}
 
  <div class="card">
    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="text-center">
              <h2 class="font-weight-bold text-dark"><i class="bi bi-emoji-frown-fill"></i> Para reservar, diríjase a la página de reservas de Kirei.</h2>
              <p class="lead text-gray-800 mb-5">El panel del staff no tiene soporte para reservar turnos en este momento.</p>
              <a href="/booking/service" class="btn btn-primary mt-3">Ir a Reservar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

kireidjangoapp/staff/templates/staff/main_dashboard.html
{% extends 'staff/base.html'%}
{% block breadcrumb-item %}<a class="breadcrumb-item" href="{% url 'staff:staff_main_dashboard'%}">Inicio</a>{% endblock %}
{% block breadcrumb-item-active %}{% endblock %} 
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="h3 mb-0 text-gray-800 d-inline-block align-middle">Inicio</h1>
</div>
{% load static %}
<div class="card">
    <div class="card-body">
    <div class="row">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header font-weight-bold text-dark">Métricas de performance</div>
          <div class="card-body">
            <div class="row">
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-primary shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                        Total ganancia reservas
                                    </div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">${{ appointment_total_revenue|default:0|floatformat:"0" }}</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-warning shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                        Total ganancias productos
                                    </div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">${{product_total_revenue|default:0|floatformat:"0" }}</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-success shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                        Cantidad total de usuarios
                                    </div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{customer_count}}</div>
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-md-6 mb-4">
                    <div class="card border-left-danger  shadow h-100 py-2">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                                        Servicio más reservado
                                    </div>
                                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                                      {{ most_booked_service|default:"Datos no disponible" }}
                                    </div>                                    
                                </div>
                                <div class="col-auto">
                                    <i class="fas fa-calendar fa-2x text-gray-300"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header font-weight-bold text-dark">Actividades recientes</div>
          <div class="card-body">
            <ul class="list-group">
              <li class="list-group-item">
                <span class="font-weight-bold">Nueva orden:</span>
                <span class="float-right">#{{ last_order.cart_payment.id }}-{{ last_order.cart_payment.created }}</span>
              </li>
              <li class="list-group-item">
                <span class="font-weight-bold">Última reserva:</span>
                <span class="float-right">{{ last_appointment.created }}</span>
              </li>
              <li class="list-group-item">
                <span class="font-weight-bold">Nuevo cliente:</span>
                <span class="float-right">{{ last_user.first_name }} {{ last_user.last_name }}</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
      
    </div>
    <div class="row mt-4">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header font-weight-bold text-dark">Accesos rápidos</div>
            <div class="card-body">
              <a href="{% url 'products:create_product' %}" class="btn btn-primary mr-2">
                <i class="bi bi-plus-square-fill"></i> Crear nuevo producto
              </a>
              <a href="{% url 'agendas:all_agenda'%}" class="btn btn-primary mr-2">
                <i class="bi bi-book"></i> Modificar agenda del profesional
              </a>
              <a href="{% url 'staff:staff_statistic_dashboard' %}" class="btn btn-primary">
                <i class="bi bi-clipboard-data"></i> Ver estadísticas
              </a>
            </div>
          </div>
        </div>
    </div>
      

</div>
</div>

{% endblock %}

kireidjangoapp/staff/templates/staff/orders_dashboard.html
{% extends 'staff/base.html'%}
{% block breadcrumb-item %}<a class="breadcrumb-item" href="{% url 'staff:staff_orders_dashboard'%}">Órdenes de compra</a>{% endblock %}
{% block breadcrumb-item-active %}Todas las órdenes de compra{% endblock %}
{% block content %}
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1 class="h3 mb-0 text-gray-800 d-inline-block align-middle">Todas las órdenes de compra</h1>
    </div>

    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            {% if orders %}
                                {% for order in orders %}
                                    <div class="container mb-4">
                                        <div class="card">
                                            <div class="card-header">
                                                <h5><span>{{ order.created_at|date }} | #{{ order.id }}</span></h5>
                                            </div>
                                            {% for product_payment in order.payment.productpayment_set.all %}
                                                <div class="list-item py-3 px-4 d-flex align-items-center border">
                                                    <div class="list-item__product d-flex align-items-center mb-4">
                                                        <div class="list-item__image mr-3">
                                                            <img src="{{ product_payment.product.image.url }}" alt="{{ product_payment.product.name }}" class="img-fluid" style="max-width: 100px; height: auto;">
                                                        </div>
                                                        <div class="list-item__data ml-4 mr-1" style="width: 37vw;">
                                                            <p class="list-item__link mb-1">
                                                                <span>{{ product_payment.product.name }}</span>
                                                            </p>
                                                            <p class="list-item__info mb-1">
                                                                <span>{{ product_payment.quantity }} unidad(es)</span>
                                                            </p>
                                                        </div>
                                                        <div class="bf-ui-button-container d-flex justify-content-center align-items-center flex-column my-2">
                                                            <a href="{% url 'staff:orders_details' order_id=order.id product_id=product_payment.product_id %}" class="btn btn-primary my-2 mr-2 w-100">Ver compra</a>
                                                            <a href="{% url 'invoices:generate_invoice' order_id=order.id product_id=product_payment.product_id%}" target="_blank" class="btn btn-secondary my-2 mr-2 w-100">Descargar factura</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <p>No se ha realizado ninguna compra aún.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

    {% endblock %}

kireidjangoapp/staff/templates/staff/staff_statistic_dashboard.html
{% extends 'staff/base.html'%}
{% block breadcrumb-item %}<a class="breadcrumb-item" href="{% url 'staff:staff_statistic_dashboard'%}">Estadísticas</a>{% endblock %}
{% block breadcrumb-item-active %}Todos las estadísticas{% endblock %}
{% block content %}
{% load static %}
{%load plotly_dash%}

<div class="container-fluid">
    {% plotly_app name='staff_statistic_dashboard' ratio=1%}
</div>

{% endblock %}