kireidjangoapp/appointments/urls.py
from django.urls import path

from appointments import views

from django.contrib.auth import views as auth_views


app_name = "appointments"

urlpatterns = [
    path("booking/all/", views.all_appointments, name="all_appointments"),
    path("booking/cancel/", views.cancel_appointment, name="cancel_appointment"),
    path("booking/service/", views.choose_service, name="choose_service"),
    path(
        "booking/professional/",
        views.choose_professional,
        name="choose_professional",
    ),
    path("booking/calendar/", views.calendar, name="calendar"),
    path("booking/slot/", views.ChooseSlotView.as_view(), name="choose_slot"),
    path("booking/checkout/", views.checkout, name="checkout"),
    path("booking/detail/", views.appointment_detail, name="appointment_detail"),
    path("booking/success/", views.mercado_pago_success, name="mercado_pago_success"),
    path("booking/failure/", views.mercado_pago_failure, name="mercado_pago_failure"),
]

kireidjangoapp/carts/urls.py
from django.urls import path
from . import views

app_name = "carts"


urlpatterns = [
    path("cart/add/<int:id>/", views.cart_add, name="cart_add"),
    path(
        "cart/item_clear/<int:id>/<str:redirect_url>/",
        views.item_clear,
        name="item_clear",
    ),
    path(
        "cart/item_increment/<int:id>/<str:redirect_url>/",
        views.item_increment,
        name="item_increment",
    ),
    path(
        "cart/item_decrement/<int:id>/<str:redirect_url>/",
        views.item_decrement,
        name="item_decrement",
    ),
    path("cart/cart_clear/", views.cart_clear, name="cart_clear"),
    path("cart/cart_detail/", views.cart_detail, name="cart_detail"),
    path(
        "cart/many_items_add/<int:id>/<int:quantity>/",
        views.many_items_add,
        name="many_items_add",
    ),
    path(
        "cart/catalog_item_increment/<int:id>/",
        views.catalog_item_increment,
        name="catalog_item_increment",
    ),
    path(
        "cart/replace_items_quantity/<int:id>/<int:quantity>/",
        views.replace_items_quantity,
        name="replace_items_quantity",
    ),
    path("cart/checkout/", views.cart_checkout, name="cart_checkout"),
    path("cart/success/", views.mercado_pago_success, name="mercado_pago_success"),
    path("cart/failure/", views.mercado_pago_failure, name="mercado_pago_failure"),
    path("cart/pending/", views.mercado_pago_pending, name="mercado_pago_pending"),
]

kireidjangoapp/home/urls.py
from django.urls import path, include

from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("services/", views.services_index, name="services"),
    path("nosotros/", views.kirei_info, name="kirei_info"),
    path("faq/", views.faq, name="faq"),
]

kireidjangoapp/kireidjangoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("payments/", include("payments.urls")),
    path("", include("home.urls")),
    path("", include(("customers.urls", "customers"), namespace="customers")),
    path("", include(("carts.urls", "carts"), namespace="carts")),
    path("", include(("products.urls", "products"), namespace="products")),
    path("", include(("agendas.urls", "agendas"), namespace="agendas")),
    path("", include(("staff.urls", "staff"), namespace="staff")),
    path("", include(("appointments.urls", "appointments"), namespace="appointments")),
    path("", include(("orders.urls", "orders"), namespace="orders")),
    path("", include(("invoices.urls", "invoices"), namespace="invoices")),
    path("", include(("services.urls", "services"), namespace="services")),
    path(
        "", include(("professionals.urls", "professionals"), namespace="professionals")
    ),
    path("django_plotly_dash/", include("django_plotly_dash.urls")),
]

urlpatterns += staticfiles_urlpatterns()

kireidjangoapp/products/urls.py
from django.urls import path
from . import views
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

app_name = "products"
urlpatterns = [
    path("products/", views.product_catalog, name="product_catalog"),
    path(
        "products/<slug:product_name>-<int:product_id>/",
        views.product_detail,
        name="product_detail",
    ),
    path("staff/product/all", views.all_product, name="all_product"),
    path("staff/product/create", views.create_product, name="create_product"),
    path("staff/product/<int:pk>/edit/", views.edit_product, name="edit_product"),
    path("staff/product/<int:pk>/delete/", views.delete_product, name="delete_product"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kireidjangoapp/carts/views.py
import json
from django.shortcuts import render, redirect
from products.models import Product
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
from django.http import HttpResponseBadRequest
from my_payments.models import ProductPayment, CartPayment
from payments.models import PaymentStatus
from customers.models import Customer
from orders.models import ProductOrder, AppointmentOrder
import mercadopago


@login_required(login_url="/login")
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("home:index")


@login_required(login_url="/login")
def item_clear(request, id, redirect_url):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect(redirect_url)


@login_required(login_url="/login")
def item_increment(request, id, redirect_url):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect(redirect_url)


@login_required(login_url="/login")
def item_decrement(request, id, redirect_url):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect(redirect_url)


@login_required(login_url="/login")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("carts:cart_detail")


@login_required(login_url="/login")
def cart_detail(request):
    return render(request, "carts/cart_detail.html")


@login_required(login_url="/login")
def many_items_add(request, id, quantity):
    print("cantidad: ", quantity)
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.adding_many(product=product, quantity=quantity)
    return redirect("carts:cart_detail")


@login_required(login_url="/login")
def replace_items_quantity(request, id, quantity):
    print("cantidad: ", quantity)
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.replace(product=product, quantity=quantity)
    return redirect("carts:cart_detail")


@login_required(login_url="/login")
def catalog_item_increment(request, id):
    cart = Cart(request)
    print("cart: ", cart)
    product = Product.objects.get(id=id)
    print("product: ", product)
    cart.add(product=product)
    return redirect("products:product_catalog")

from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib import messages
@login_required(login_url="/login")
def cart_checkout(request):
    cart = Cart(request)

    if request.method == "POST":
        payment_method = request.POST.get("payment_method")
        request.session["payment_method"] = payment_method
        customer = Customer.objects.get(id=request.user.id)
        payment_method = request.session.get("payment_method")
        mercado_pago_payment_id = request.GET.get("payment_id")

        if payment_method == "mercadopago":
            # PROD_ACCESS_TOKEN needed
            sdk = mercadopago.SDK("")

            # Create items in the preference
            items = []

            if isinstance(cart.cart, str):
                cart_dict = json.loads(cart.cart)
            else:
                cart_dict = cart.cart

            for item in cart_dict.values():
                print("item: ", item)
                product_id = item["product_id"]
                quantity = item["quantity"]

                product = Product.objects.get(id=product_id)

                item_data = {
                    "title": product.name,
                    "quantity": quantity,
                    "unit_price": float(product.price),
                    "currency_id": "ARS",
                }
                items.append(item_data)
            

            preference_data = {
                "items": items,
                "back_urls": {
                    "success": "http://127.0.0.1:8000/cart/success/",
                    "failure": "http://127.0.0.1:8000/cart/failure",
                    "pending": "https://127.0.0.1:8000/cart/pending",
                },
                "auto_return": "approved",
                "binary_mode": True,
            }

            preference_response = sdk.preference().create(preference_data)
            preference = preference_response["response"]

            # Pass the item IDs to the template context
            item_ids = [item["id"] for item in preference["items"]]
            return render(
                request,
                "carts/mercado_pago.html",
                {
                    "item_ids": item_ids,
                    "item_id": preference["id"],
                },
            )

        elif payment_method == "cash":
            customer = Customer.objects.get(id=request.user.id)

            # Create a new CartPayment object
            cart_payment = CartPayment.objects.create(
                payment_method=payment_method,
                id_mercado_pago=mercado_pago_payment_id,
                status=PaymentStatus.CONFIRMED,
                currency="ARS",
                billing_first_name=customer.first_name,
                billing_last_name=customer.last_name,
                billing_email=customer.email,
                billing_phone=customer.phone_number,
            )

            if isinstance(cart.cart, str):
                cart_dict = json.loads(cart.cart)
            else:
                cart_dict = cart.cart

            # Iterate through the items in the cart
            cart_total = 0
            for item in cart_dict.values():
                product_id = item["product_id"]
                quantity = item["quantity"]

                product = Product.objects.get(id=product_id)

                # Create a new ProductPayment object
                product_payment = ProductPayment.objects.create(
                    product=product,
                    cart_payment=cart_payment,
                    quantity=quantity,
                    total=product.price * quantity
                   
                )

                # Update the stock of the product
                product.stock -= quantity
                product.save()

                # Add the ProductPayment object to cart_products field
                cart_payment.cart_products.add(product)

                cart_total += product_payment.total

            # Update the CartPayment object's total field with the sum of the totals for each ProductPayment
            cart_payment.cart_total = cart_total
            cart_payment.save()

            # Create the order object with customer information
            order = ProductOrder.objects.create(
                customer=customer,
                payment=cart_payment,
            )

            # Store the order id in the session for later reference
            request.session["order_id"] = order.id

            # Prepare the context data to pass to the template
            context = {
                "order": order,
            }

            # Render the HTML content of the email template
            html_message = render_to_string("carts/cart_detail_email.html", context)

            # Strip the HTML tags to generate the plain text version of the email
            plain_message = strip_tags(html_message)

            # Send the email
            send_mail(
                subject="Usted ha realizado una compra en Kirei",
                message=plain_message,
                from_email="hola@kirei.com", 
                recipient_list=[customer.email],  
                html_message=html_message,
                fail_silently=False,
            )

            cart.clear()

            return render(
                request,
                "orders/order_detail.html",
                {"order": order},
            )

        else:
            return messages.error(request, "Error en el método de pago. Intente más tarde.")

    return render(
        request,
        "carts/cart_checkout.html",
        {"cart": cart},
    )


@login_required(login_url="/login")
def mercado_pago_success(request):
    payment_method = request.session.get("payment_method")
    mercado_pago_payment_id = request.GET.get("payment_id")
    merchant_order_id = request.GET.get("merchant_order_id")

    cart = Cart(request)

    customer = Customer.objects.get(id=request.user.id)

    # Create a new CartPayment object
    cart_payment = CartPayment.objects.create(
        payment_method=payment_method,
        id_mercado_pago=mercado_pago_payment_id,
        status=PaymentStatus.CONFIRMED,
        currency="ARS",
        billing_first_name=customer.first_name,
        billing_last_name=customer.last_name,
        billing_email=customer.email,
        billing_phone=customer.phone_number,
    )

    if isinstance(cart.cart, str):
        cart_dict = json.loads(cart.cart)
    else:
        cart_dict = cart.cart

    cart_total = 0
    for item in cart_dict.values():
        product_id = item["product_id"]
        quantity = item["quantity"]

        product = Product.objects.get(id=product_id)

        # Create a new ProductPayment object
        product_payment = ProductPayment.objects.create(
            product=product,
            cart_payment=cart_payment,
            quantity=quantity,
            total=product.price * quantity,
        )

        # Update the stock of the product
        product.stock -= quantity
        product.save()

        # Add the ProductPayment object to cart_products field
        cart_payment.cart_products.add(product)

        cart_total += product_payment.total

    # Update the CartPayment object's total field with the sum of the totals for each ProductPayment
    cart_payment.cart_total = cart_total
    cart_payment.save()

    # Create the order object with customer information
    order = ProductOrder.objects.create(
        customer=customer,
        payment=cart_payment,
    )

kireidjangoapp/carts/templates/carts/cart_detail.html
{% extends 'home/base.html'%}
{% load cart_tag %}
{% block content %}

<div class="container mt-5 pt-5">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active text-secondary" id="cart-tab" data-bs-toggle="tab" data-bs-target="#cart" type="button" role="tab" aria-controls="cart" aria-selected="true">Carrito ({{ cart_total_quantity }})</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link text-secondary" id="saved-tab" data-bs-toggle="tab" data-bs-target="#saved" type="button" role="tab" aria-controls="saved" aria-selected="false">Guardados (0)</button>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="cart" role="tabpanel" aria-labelledby="cart-tab">
        {% if request.session.cart.items %}
          <div class="card-header row align-items-center cart mb-3">
              {% for key, value in request.session.cart.items %}
                <div class="card">
                  <div class="row g-0">
                    <div class="col-md-6 col-sm-12 mb-3 mb-md-0">
                      <div class="d-flex">
                        <div class="col-md-3 col-sm-12">
                          <a href="{% url 'products:product_detail' product_name=value.name|slugify product_id=value.product_id %}">
                          <img src="{{ value.image }}" class="card-img m-3" alt="{{ value.name }}">
                          </a>
                        </div>
                        <div class="col-md-9 col-sm-12 my-4 mb-md-0 pb-5">
                          <div class="card-body" >
                            <h5 class="card-title mb-4 font-weight-bold" >
                              <a href= "{% url 'products:product_detail' value.name|slugify value.product_id %}" style="color: black; text-decoration: none !important;">
                              {{ value.name }}
                              </a>
                            </h5>
                            <a href="{% url 'carts:item_clear' value.product_id 'carts:cart_detail'%}" class="btn btn-danger btn-sm mx-1 bg-danger"><i class="bi bi-x-circle-fill"></i> Eliminar</a>
                            <button type="button" class="btn btn-secondary btn-sm mx-1 bg-secondary">Guardar para después</button>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-12 my-4 mb-md-0 d-flex align-items-center justify-content-center flex-column">
                      {% if value.quantity < value.stock %}
                      <div class="btn-group" role="group">
                        {% if value.quantity > 1 %}
                            <a class="btn btn-outline-secondary" href="{% url 'carts:item_decrement' value.product_id 'carts:cart_detail'%}"><i class="bi bi-dash-circle-fill"></i></a>
                            {% else %}
                            <a class="btn btn-outline-secondary" href="{% url 'carts:item_clear' value.product_id 'carts:cart_detail'%}"><i class="bi bi-trash"></i></a>
                        {% endif %}
                            <input type="text" id="quantity-input-{{ value.product_id }}" class="form-control text-center quantity-input" name="quantity" min="1" max="{{ value.stock }}" value="{{ value.quantity }}" required />
                            <a class="btn btn-outline-secondary" href="{% url 'carts:item_increment' value.product_id 'carts:cart_detail'%}"><i class="bi bi-plus-circle-fill"></i></a>
                      </div> 
                      <div id="text-quantity-message" class="text-center text-muted mt-2">
                        {{ value.stock|sub:value.quantity }} disponibles
                        </div>
                      {% else %}
                      <div class="btn-group" role="group">
                      <a class="btn btn-outline-secondary" href="{% url 'carts:item_decrement' value.product_id 'carts:cart_detail' %}"><i class="bi bi-dash-circle-fill"></i></a>
                        <input type="text" id="quantity-input-{{ value.product_id }}" class="form-control text-center quantity-input" name="quantity" min="1" max="{{ value.stock }}" value="{{ value.quantity }}"/>
                        <a class="btn btn-outline-secondary" href="" disabled><i class="bi bi-plus-circle-fill"></i></a>
                      </div>             
                        <div class="text-center text-danger mt-2" id="text-quantity-message"><strong>{{ value.stock|sub:value.quantity }} disponibles</strong></div>
                      {% endif %}
                    </div>
                    <div class="col-md-3 col-sm-12 my-4 mb-md-0 pb-5 d-flex align-items-center justify-content-center">
                      <div class="card-price d-flex align-items-center">
                        <h4 class="card-text"><h4 class="card-text">${{ value.price|multiply:value.quantity|floatformat:"0" }}</h4>
                      </h4>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
          </div>
          <div class="card row mb-5">
            <div class="col-md-12 my-5">
              {% comment %} <div class="row align-items-center justify-content-end ">
                <div class="col-md-10 text-right">
                  <h6 class="text-uppercase font-weight-bold">Envío</h6>
                </div>
                <div class="col-md-2 text-right">
                  <h7 class="font-weight-bold">Retiro en el establecimiento</h7>
                </div>
              </div>
              <hr class="my-5"> 
              {% endcomment %}
              <div class="row align-items-center justify-content-end mb-4">
                <div class="col-md-10 text-right">
                  <h3 class="text-uppercase font-weight-bold">Total</h3>
                </div>
                <div class="col-md-2 text-right">
                  <h4 class="font-weight-bold">${{ cart_total_amount|floatformat:"0" }}</h4>
                </div>
              </div>
              <hr class="my-5">
              <a class="btn btn-primary float-md-right bg-primary" href="{% url 'carts:cart_checkout'%}">Continuar al pago</a>
            </div>
          </div>
        {% else %}
          <div class="card mb-3 py-5">
              <div class="empty-tab-content text-center">
                  <h2 class="card-title fw-bold pt-5 mb-3">Tu carrito está vacío</h2>
                  <p class="card-text mb-4">¿No sabés qué comprar? ¡Muchos de productos te esperan!</p>
                  <a class="btn btn-primary" href="{% url 'products:product_catalog'%}">Comprar productos</a>
              </div>   
          </div> 
        {% endif %}
      </div>
      <div class="tab-pane fade" id="saved" role="tabpanel" aria-labelledby="saved-tab">
        <div class="card mb-3 py-5">
          <div class="card-body text-center">
            <h2 class="card-title fw-bold pt-5 pb-3">No tenés productos guardados.</h2>
            <p class="card-text mb-4">Si aún no te decidiste a comprar algún producto de tu carrito, podés dejarlo acá para no perderlo.</p>
            <a class="btn btn-primary" href="{% url 'products:product_catalog'%}">Comprar productos</a>
          </div>
        </div>
      </div>
    </div>
</div>

  <script>
    const quantityInputs = document.querySelectorAll('.quantity-input');
    
    quantityInputs.forEach(input => {
        input.addEventListener('change', () => {
            const productId = input.id.split('-')[2];
            const maxQuantity = input.max;
            const quantity = parseInt(input.value);
    
            console.log(document.getElementById('text-quantity-message'));
            setTimeout(()=>{

            },10000)
            if (quantity > maxQuantity) {

                input.disabled = false;
                document.getElementById('text-quantity-message').innerHTML = 'Supera las unidades disponibles';

            } else if (quantity < 1) {
              document.getElementById('text-quantity-message').innerHTML = 'Puedes comprar desde 1 unidad.';

            } else {

                // construct the URL with the quantity and product ID
                var url = '/carts/replace_items_quantity/' + productId + '/' + quantity + '/';

                // redirect to the URL
                window.location.href = url;
            }
        });
    });
    </script>
    

{% endblock %}

kireidjangoapp/carts/templates/carts/cart_detail_email.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- All of the CSS -->
    <!-- Start CSS -->   
    
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/@glidejs/glide/dist/css/glide.core.min.css">


    <script src="https://cdn.jsdelivr.net/npm/@glidejs/glide/dist/glide.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/14.6.3/nouislider.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/14.6.3/nouislider.min.js"></script>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Others CSS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;600&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/bootstrap-slider.min.js" integrity="sha512-f0VlzJbcEB6KiW8ZVtL+5HWPDyW1+nJEjguZ5IVnSQkvZbwBt2RfCBY0CBO1PsMAqxxrG4Di6TfsCPP3ZRwKpA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Footer CSS -->

    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.4/index.global.min.js'></script>
    <script src="https://sdk.mercadopago.com/js/v2"></script>


<!-- End CSS -->
  <!-- Title -->
    <title>Reserva pendiente de pago</title>
    
  </head>
 <body>
    <div class="container my-5 py-5">
        <div class="row justify-content-center">
          <div class="col-md-8">
            <div class="card p-4">
              <h5 class="card-title mb-4 text-center"><strong>Su compra ha sido realizada exitosamente y se encuentra pendiente de pago.</strong></h5>
      
              <p class="card-text text-center">Nro de Orden: #{{ order.id }} - {{ order.payment.created }}</p>
      
              <div class="card-header row align-items-center cart mb-3">
                {% for product_payment in order.payment.productpayment_set.all %}
                  <div class="card mb-3">
                    <div class="row g-0">
                      <div class="col-md-6 col-sm-12 mb-3 mb-md-0 d-flex justify-content-center align-items-center">
                        {% comment %} <a href="{% url 'products:product_detail' product_name=product_payment.product.name|slugify product_id=product_payment.product_id %}">
                          <img src="{{ product_payment.product.image.url }}" class="card-img m-3" alt="{{ product_payment.product.name }}" style="max-height: 200px;">
                        </a> {% endcomment %}
                      </div>
                      <div class="col-md-6 col-sm-12 my-4 mb-md-0 pb-5">
                        <div class="card-body">
                          <h5 class="card-title mb-4 font-weight-bold">
                            <a href= "" style="color: black; text-decoration: none !important;">
                              {{ product_payment.product.name }}
                            </a>
                          </h5>
                          <p class="card-text">{{ product_payment.quantity }} uds. x ${{ product_payment.product.price }}</p>
                          <h4 class="card-text font-weight-bold">$ {{ product_payment.total }}</h4>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              </div>
      
              <div class="card row mb-5">
                <div class="col-md-12 my-5">
                  <div class="row align-items-center justify-content-end mb-4">
                    <div class="col-md-9 text-right">
                      <h3 class="text-uppercase font-weight-bold">Total</h3>
                    </div>
                    <div class="col-md-3 text-right">
                      <h4 class="font-weight-bold">${{ order.payment.cart_total }}</h4>
                    </div>
                  </div>
                </div>
              </div>
      
              <div class="card-header">
                <p class="card-text text-center"><strong>Realice el pago en efectivo en el establecimiento (Av.Directorio 3217, 8vo "C").</strong></p>
              </div>
      
            </div>
          </div>
        </div>
      </div>
    <!-- Specific js -->
      {% block scripts %}{% endblock %}
    <!-- More Javascript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
        integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
        integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK"
        crossorigin="anonymous"></script>
  </body>
</html>